### ISSUE TITLE
Implement combine for non-linear functions

### ISSUE THREAD

**Issue by LaRiffle** [arkhn/dsPrivacy#10]
## Problem

`combine` is the functionality that aggregates the results from different locations (on the client side, so this doesn't provide any extra privacy, unless we use private aggregration in the future).

It's a follow-up work after #5 

## Implementation

Here is the list of functions currently implemented and missing their combine argument:
- [x] median
- [x] standard deviation
- [x] variance
- [x] covariance
- [x] Student or T-test

**Comment by naudinlo** [comment]
Linked to:
- https://github.com/arkhn/dsPrivacyClient/pull/5
- https://github.com/arkhn/dsPrivacy/pull/17
