### ISSUE TITLE
Implement Student Test with DP

### ISSUE THREAD

**Issue by LaRiffle** [arkhn/dsPrivacy#6]
# Context

Student test (or T-test) is supported by default by [dsStats](https://rdrr.io/github/datashield/dsStatsClient/man/ds.tTest.html), but not the DP version

# Details

We acknowledge that the combine functionality might go somewhat beyond the scope of this issue, which rather focuses on developing a simple but correct implementation of the protocol, which particularly addresses the sharing of the budget epsilon between the different sub-operations.

For implementation guidance, the PRs on the covariance can be leveraged:
- https://github.com/arkhn/dsPrivacy/issues/3
- https://github.com/arkhn/dsPrivacyClient/pull/1

**Comment by naudinlo** [comment]
PR: 
- https://github.com/arkhn/dsPrivacyClient/pull/4
- https://github.com/arkhn/dsPrivacy/pull/16
