### ISSUE TITLE
Test import from datamart in DataShield

### ISSUE THREAD

**Issue by Jasopaum** [arkhn/dsPrivacy#7]
### Objective

In an ideal world, we would like to create an isolated environment with a datamart loaded in Opal, directly in Arkhn Admin.

### Steps

TODO : possible to specify a dedicated schema? 

To do so, we need to:
- [ ] Learn how to load automatically data in an Opal Server (from a DB, from a csv?)
- [ ] Based on the load method, create a script for Arkhn Admin that will:
        1) export a pseudonymized datamart 
        2) load the datamart in Opal _on a remote VM_.

**Comment by LaRiffle** [comment]
3 levels of authentication

1. Get access to a remote `schema.table` on Opal

- [ ] check that we can use a non default schema

2. Create DataShield Users ☑ 


3. Create separate workspace for all investigators so that they have their separate R or jupyter notebooks
